| FIX TEST | Error occured after Typo fix in JsxObserver.createInitialAdditions ()
AssertionError: expected 'a<!--undefined-->b' to equal 'ab'
jsx[1] was undefined so a comment node was added with text undefined